name: winghelper

services:
  winghelper:
    build:
      dockerfile: Dockerfile
    devices:
      - /dev/dri:/dev/dri:rwm
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${HOME}/.Xauthority:/ubuntu/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./Documents/:/home/ubuntu/Documents/:rw
